export 'package:inaltosalud/widgets/alergias_container_detail.dart';
export 'package:inaltosalud/widgets/dermoestetica_container_detail.dart';
export 'package:inaltosalud/widgets/lactancia_container_detail.dart';
export 'package:inaltosalud/widgets/global_bottombar.dart';
export 'package:inaltosalud/widgets/global_appbar.dart';
export 'package:inaltosalud/widgets/home_container_1.dart';
export 'package:inaltosalud/widgets/home_container_2.dart';
export 'package:inaltosalud/widgets/home_container_3.dart';
export 'package:inaltosalud/widgets/global_links.dart';
